### ISSUE TITLE
compatible with IDEA 2024.1

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm-tools/ebean-idea-enhancer#9]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.ebean.tool.ideaagent.ToggleAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.avaje.ebean11.enhancer]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by rbygrave** [comment]
Try this new version -  https://plugins.jetbrains.com/plugin/10082-ebean-enhancer/versions/stable/518994

It is not yet approved by Jetbrains, it usually takes 2 days to approve a new version of the plugin.

**Comment by spinachomes** [comment]
got it,thanks

**Comment by rbygrave** [comment]
Ok, I think we can close this as fixed in version 14.2.1 of the plugin
